language: android
jdk: oraclejdk8
env:
  matrix:
    - KSTOREPWD="123456" KEYPWD="123456"
android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

script:
   - ./gradlew build connectedCheck
