package io.supersimple.notes.test;


public interface Cities {
    String[] B = {
            "Bab Ezzouar",
            "Babol",
            "Babruysk",
            "Bacău",
            "Bacolod",
            "Bacoor",
            "Badajoz",
            "Badalona",
            "Bafoussam",
            "Bagé",
            "Baghdad",
            "Bago City",
            "Bago",
            "Baguio",
            "Baharampur",
            "Bahawalnagar",
            "Bahawalpur",
            "Bahía Blanca",
            "Bahir Dar",
            "Bahraich",
            "Baia Mare",
            "Baicheng",
            "Baidoa",
            "Baise",
            "Baishan",
            "Baiyin",
            "Bakersfield",
            "Baku",
            "Balakovo",
            "Balashikha",
            "Baleshwar",
            "Balıkesir",
            "Balikpapan",
            "Baliuag",
            "Bally",
            "Bălți",
            "Baltimore",
            "Balurghat",
            "Bamako",
            "Bamenda",
            "Banda Aceh",
            "Bandar Abbas",
            "Bandırma",
            "Bandung",
            "Bangalore",
            "Bangkok",
            "Bangui",
            "Banha",
            "Bani Suwayf",
            "Banja Luka",
            "Banjarmasin",
            "Banjul",
            "Bankura",
            "Baoding",
            "Baoji",
            "Baoshan",
            "Baotou",
            "Barakaldo",
            "Baraki",
            "Baranagar",
            "Baranovichi",
            "Barbacena",
            "Barcelona",
            "Barcelona",
            "Bardhaman",
            "Bareilly",
            "Bari",
            "Barika",
            "Barinas",
            "Barisal",
            "Barnaul",
            "Barquisimeto",
            "Barra Mansa",
            "Barrackpur",
            "Barrancabermeja",
            "Barranquilla",
            "Barreiras",
            "Barretos",
            "Barrie",
            "Barueri",
            "Baruta",
            "Barysaw",
            "Basel",
            "Basirhat",
            "Basra",
            "Bat Yam",
            "Batala",
            "Batam",
            "Batangas City",
            "Bataysk",
            "Bath",
            "Bathinda",
            "Batman",
            "Batna",
            "Baton Rouge",
            "Battambang",
            "Batumi",
            "Bauru",
            "Bayambang",
            "Bayamo",
            "Bayamón",
            "Bayannur",
            "Bayawan",
            "Baybay",
            "Bazhou",
            "Beau-Bassin",
            "Beaumont",
            "Beauvais",
            "Beawar",
            "Béchar",
            "Beed",
            "Beersheba",
            "Bei\'an",
            "Beihai",
            "Beijing",
            "Beipiao",
            "Beirut",
            "Béjaïa",
            "Belém",
            "Belfast",
            "Belgaum",
            "Belgorod",
            "Belgrade",
            "Bellary",
            "Bellevue",
            "Bello",
            "Belo Horizonte",
            "Bengbu",
            "Benghazi",
            "Benguela",
            "Beni Mellal",
            "Benito Juárez",
            "Benoni",
            "Benxi",
            "Beppu",
            "Berbera",
            "Berdyansk",
            "Berezniki",
            "Bergamo",
            "Bergen",
            "Bergisch Gladbach",
            "Berhampur",
            "Berkeley",
            "Berlin",
            "Bern",
            "Besançon",
            "Betim",
            "Bettiah",
            "Bhadravati",
            "Bhagalpur",
            "Bhalwal",
            "Bharatpur",
            "Bharatpur",
            "Bharuch",
            "Bhatpara",
            "Bhavnagar",
            "Bhilai",
            "Bhilwara",
            "Bhimavaram",
            "Bhind",
            "Bhiwandi",
            "Bhiwani",
            "Bhopal",
            "Bhubaneswar",
            "Bhuj",
            "Bhusawal",
            "Białystok",
            "Bidar",
            "Bielefeld",
            "Bielsko-Biała",
            "Bihar Sharif",
            "Bijapur",
            "Bikaner",
            "Bila Tserkva",
            "Bilaspur",
            "Bilbao",
            "Billings",
            "Biñan",
            "Binangonan",
            "Binzhou",
            "Biratnagar",
            "Birjand",
            "Birmingham",
            "Birmingham",
            "Bishkek",
            "Bislig",
            "Biskra",
            "Bissau",
            "Biysk",
            "Bizerte",
            "Blackburn",
            "Blackpool",
            "Blagoveshchensk",
            "Blantyre",
            "Blida",
            "Bloemfontein",
            "Blumenau",
            "Bnei Brak",
            "Boa Vista",
            "Bobo-Dioulasso",
            "Bocaue",
            "Bochum",
            "Bogor",
            "Bogota",
            "Bogra",
            "Boise",
            "Bojnord",
            "Bokaro Steel City",
            "Boksburg",
            "Bole",
            "Bologna",
            "Bolton",
            "Boma",
            "Bonn",
            "Bordeaux",
            "Bordj Bou Arréridj",
            "Bordj El Kiffan",
            "Borujerd",
            "Bosaso",
            "Boston",
            "Botoșani",
            "Botou",
            "Botshabelo",
            "Bottrop",
            "Botucatu",
            "Bou Saâda",
            "Bouaké",
            "Boulder",
            "Boulogne-Billancourt",
            "Bourg-en-Bresse",
            "Bournemouth",
            "Bozhou",
            "Bradford",
            "Braga",
            "Bragança Paulista",
            "Brăila",
            "Brampton",
            "Brasília",
            "Brașov",
            "Bratislava",
            "Bratsk",
            "Braunschweig",
            "Brazzaville",
            "Breda",
            "Bremen",
            "Bremerhaven",
            "Brescia",
            "Brest",
            "Brest",
            "Bridgeport",
            "Brighton",
            "Brisbane",
            "Bristol",
            "Brno",
            "Brownsville",
            "Bruges",
            "Brussels",
            "Bryansk",
            "Bucaramanga",
            "Bucharest",
            "Bucheon",
            "Budapest",
            "Budaun",
            "Buenaventura",
            "Buenos Aires",
            "Buffalo",
            "Buga",
            "Bujumbura",
            "Bukan",
            "Bukavu",
            "Bukhara",
            "Bulandshahr",
            "Bulawayo",
            "Buôn Ma Thuột",
            "Burao",
            "Burbank",
            "Burewala",
            "Burgas",
            "Burgos",
            "Burhanpur",
            "Burlington",
            "Burnaby",
            "Bursa",
            "Bury",
            "Busan",
            "Bushehr",
            "Butuan",
            "Buzău",
            "Bydgoszcz",
            "Bytom",
            "Butwal"
    };
}
